apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instances.ecs.easystack.io
spec:
  group: ecs.easystack.io
  version: v1
  names:
    kind: Instance
    plural: instances
    singular: instance
    shortNames:
    - vm
  scope: Namespaced
